!!python/object/new:utils.tools.DotDict
dictitems:
  cell_type: all
  codes_dir: runs/train/qwer/2024_10_29_18_12_56_17/codes
  cuda_id: '9'
  cur_time: '2024_10_29_18_12_56_17'
  data_dir: data/suzuki_data
  description: null
  device: cuda:9
  device_info: NVIDIA L40S
  disable_wandb: true
  exp_name: qwer
  save_best_model: true
  save_dir: runs/train/qwer/2024_10_29_18_12_56_17
  seed: 42
  skip_test_prediction: false
  task_type: multi
  wandb_entity: chrenx
  wandb_pj_name: nus-mini-proj
  weights_dir: runs/train/qwer/2024_10_29_18_12_56_17/weights
