!!python/object/new:utils.tools.DotDict
dictitems:
  exp_name: qwer
  description: null
  save_dir: runs/train/qwer/2024_10_29_18_14_37_51
  wandb_pj_name: nus-mini-proj
  wandb_entity: chrenx
  disable_wandb: true
  seed: 42
  task_type: multi
  cell_type: all
  data_dir: data/suzuki_data
  cuda_id: '9'
  save_best_model: true
  skip_test_prediction: false
  cur_time: '2024_10_29_18_14_37_51'
  weights_dir: runs/train/qwer/2024_10_29_18_14_37_51/weights
  codes_dir: runs/train/qwer/2024_10_29_18_14_37_51/codes
  device_info: NVIDIA L40S
  device: cuda:9
